ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),

    path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

favsql/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

app_name = 'favsql'

urlpatterns = [
    path('', views.ThingListView.as_view(), name='things'),
    path('sql/', views.SQLListView.as_view(), name='thingsql'),
    path('thing/<int:pk>', views.ThingDetailView.as_view(), name='thing_detail'),
    path('thing/create', 
        views.ThingCreateView.as_view(success_url=reverse_lazy('favsql:things')), name='thing_create'),
    path('thing/<int:pk>/update', 
        views.ThingUpdateView.as_view(success_url=reverse_lazy('favsql:things')), name='thing_update'),
    path('thing/<int:pk>/delete', 
        views.ThingDeleteView.as_view(success_url=reverse_lazy('favsql:things')), name='thing_delete'),
    path('thing/<int:pk>/favorite', 
        views.AddFavoriteView.as_view(), name='thing_favorite'),
    path('thing/<int:pk>/unfavorite', 
        views.DeleteFavoriteView.as_view(), name='thing_unfavorite'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
#    path('', include('ads.urls')),  # Change to ads.urls
    path('ads/', include('ads.urls')),
    path('cats/', include('cats.urls')),
    path('autos/', include('autos.urls')),
    path('courses/', include('courses.urls')),
    path('api/v1/courses/', include('courses.urls')),
    path('tagme/', include('tagme.urls')),
    path('favs/', include('favs.urls')),
    path('myarts/', include('myarts.urls')),
    path('', include('home.urls')),
    path('example/', include('example.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

favsql/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings

class Thing(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='favsql_thing_owner')
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favsql_favorite_things')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title

class Fav(models.Model) :

    thing = models.ForeignKey(Thing, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='favsql_users')

    # https://docs.djangoproject.com/en/3.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('thing', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.thing.title[:10])

favsql/extra/views.py
from favs.models import Thing, Fav

from django.views import View
from django.views import generic
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Exists, OuterRef

# These are experimental views - under construction...

class ExistsListView(OwnerListView):
    template_name = "favs/expsql.html"
    def get(self, request) :
        if not request.user.is_authenticated:
            thing_list = Thing.objects.all()
        else:
            thing_list = Thing.objects.annotate(
                FAV_USER_ID=Exists(Fav.objects.filter(user=self.request.user,thing_id=OuterRef('id')))
                ).all()
        ctx = {'thing_list' : thing_list}
        return render(request, self.template_name, ctx)

# https://stackoverflow.com/questions/2314920/django-show-log-orm-sql-calls-from-python-shell
# pip install django-extensions
# ./manage.py shell_plus --print-sql

# Below this line, we see raw sql...   With great power comes great responsibility
# https://docs.djangoproject.com/en/3.0/topics/db/sql/

# A List view using raw SQL - super efficient
class RawSQLListView(OwnerListView):
    template_name = "favs/expsql.html"

    def get(self, request) :
        if not request.user.is_authenticated:
            thing_list = Thing.objects.all()
        else:
            sql = """SELECT *, favs_fav.user_id AS FAV_USER_ID FROM favs_thing
                LEFT JOIN favs_fav ON favs_thing.id = favs_fav.thing_id
                AND favs_fav.user_id = """ + str(self.request.user.id)
            print(sql)
            thing_list = Thing.objects.raw(sql)
        ctx = {'thing_list' : thing_list}
        return render(request, self.template_name, ctx)

# Notes from the shell:
# sql = "SELECT *, favs_fav.user_id AS FAV_USER_ID FROM favs_thing LEFT JOIN favs_fav ON favs_thing.id = favs_fav.thing_id AND favs_fav.user_id = 1"
# thing_list2 = Thing.objects.raw(sql)
# row0 = thing_list2[0]
# row0.FAV_USER_ID
# row1 = thing_list2[1]
# row1.FAV_USER_ID

favsql/views.py
from favsql.models import Thing, Fav

from django.views import View
from django.views import generic
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin

from myarts.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

from pprint import pprint

from django.db import connection
import re

from . import sqldebug 

class ThingListView(OwnerListView):
    model = Thing
    template_name = "favsql/list.html"

    def get(self, request) :
        thing_list = Thing.objects.all()
        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}]  (A list of rows)
            rows = request.user.favsql_favorite_things.values('id')
            favorites = [ row['id'] for row in rows ]
        ctx = {'thing_list' : thing_list, 'favorites': favorites}
        retval = render(request, self.template_name, ctx)
        
        sqldebug.print_queries()
        return retval

class SQLListView(OwnerListView):
    template_name = "favsql/list_sql.html"

    def get(self, request) :
        if not request.user.is_authenticated:
            thing_list = Thing.objects.all()
        else:
            sql = """SELECT *, favsql_fav.user_id AS FAV_USER_ID FROM favsql_thing
                LEFT JOIN favsql_fav ON favsql_thing.id = favsql_fav.thing_id
                AND favsql_fav.user_id = """ + str(self.request.user.id)
            thing_list = Thing.objects.raw(sql)

        ctx = {'thing_list' : thing_list}
        retval = render(request, self.template_name, ctx)

        sqldebug.print_queries()
        return retval

class ThingDetailView(OwnerDetailView):
    model = Thing
    template_name = "favsql/detail.html"

class ThingCreateView(OwnerCreateView):
    model = Thing
    fields = ['title', 'text']
    template_name = "favsql/form.html"
    success_url = reverse_lazy('favsql:things')

class ThingUpdateView(OwnerUpdateView):
    model = Thing
    fields = ['title', 'text']
    template_name = "favsql/form.html"
    # success_url = reverse_lazy('favsql:things')
    success_url = 'http://www.dr-chuck.com/'

class ThingDeleteView(OwnerDeleteView):
    model = Thing
    template_name = "favsql/delete.html"
    success_url = reverse_lazy('favsql:things')

# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        t = get_object_or_404(Thing, id=pk)
        fav = Fav(user=request.user, thing=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        t = get_object_or_404(Thing, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, thing=t).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

favsql/templates/favsql/delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Thing</h1>

<p>Are you sure you want to delete the thing: {{ thing }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'favsql:things' %}';return false;">
</form>
{% endblock %}

favsql/templates/favsql/detail.html
{% extends "base_bootstrap.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}
<span style="float: right;">
({{ thing.updated_at|naturaltime }})
{% if thing.owner == user %}
<a href="{% url 'favsql:thing_update' thing.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'favsql:thing_delete' thing.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ thing.title }}</h1>
<p>
{{ thing.text }}
</p>
<p>
</p>
<p>
<a href="{% url 'favsql:things' %}">All things</a>
</p>
{% endblock %}

favsql/templates/favsql/form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'favsql:things' %}';return false;">
  </form>
</p>
{% endblock %}

favsql/templates/favsql/list.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Favorite Things (Normal)</h1>
<p>
{% if thing_list %}
<ul>
  {% for thing in thing_list %}
    <li>
        <a href="{% url 'favsql:thing_detail'  thing.id %}">{{ thing.title }}</a>
        {% if thing.owner_id == user.id %}
        (<a href="{% url 'favsql:thing_update' thing.id %}">Edit</a> |
        <a href="{% url 'favsql:thing_delete' thing.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <a href="#" onclick=
            "favPost('{% url 'favsql:thing_unfavorite' thing.id %}', {{ thing.id }} );return false;"
            {% if thing.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{thing.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- Weird - fa-stack changes vertical spacing so to be consistent we use it here -->
        <a href="#" onclick=
             "favPost('{% url 'favsql:thing_favorite' thing.id %}', {{ thing.id }} );return false;"
            {% if thing.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{thing.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no things in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'favsql:thing_create' %}">Add a Thing</a> |
<a href="{% url 'favsql:thingsql' %}">Switch to SQL</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'favsql:things' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'favsql:things' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, thing_id) {
    fetch(url, {
        method: "POST", // *GET, POST, PUT, DELETE, etc.
        mode: "cors", // no-cors, cors, *same-origin
        cache: "no-cache", // *default, no-cache, reload, force-cache, only-if-cached
        credentials: "same-origin", // include, *same-origin, omit
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        redirect: "follow", // manual, *follow, error
        referrer: "no-referrer", // no-referrer, *client
    }).then(function(data) {
        console.log(url, 'finished');
        $("#unfavorite_star_"+thing_id).toggle();
        $("#favorite_star_"+thing_id).toggle();
    }).catch(function() {
        console.log(url, 'error');
    })
}
</script>
{% endblock %}

favsql/templates/favsql/list_sql.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Favorite Things (SQL)</h1>
<p>
{% if thing_list %}
<ul>
  {% for thing in thing_list %}
    <li>
        <a href="{% url 'favsql:thing_detail'  thing.id %}">{{ thing.title }}</a>
        {% if thing.owner_id == user.id %}
        (<a href="{% url 'favsql:thing_update' thing.id %}">Edit</a> |
        <a href="{% url 'favsql:thing_delete' thing.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <a href="#" onclick=
            "favPost('{% url 'favsql:thing_unfavorite' thing.id %}', {{ thing.id }} );return false;"
            {% if not thing.FAV_USER_ID %} style="display: none;" {% endif %}
            id="favorite_star_{{thing.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <a href="#" onclick=
             "favPost('{% url 'favsql:thing_favorite' thing.id %}', {{ thing.id }} );return false;"
            {% if thing.FAV_USER_ID %} style="display: none;" {% endif %}
            id="unfavorite_star_{{thing.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <!-- Weird - fa-stack changes vertical spacing so to be consistent we use it here -->
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no things in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'favsql:thing_create' %}">Add a Thing</a> |
<a href="{% url 'favsql:things' %}">Switch to Non-SQL</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'favsql:things' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'favsql:things' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, thing_id) {
    fetch(url, {
        method: "POST", // *GET, POST, PUT, DELETE, etc.
        mode: "cors", // no-cors, cors, *same-origin
        cache: "no-cache", // *default, no-cache, reload, force-cache, only-if-cached
        credentials: "same-origin", // include, *same-origin, omit
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        redirect: "follow", // manual, *follow, error
        referrer: "no-referrer", // no-referrer, *client
    }).then(function(data) {
        console.log(url, 'finished');
        $("#unfavorite_star_"+thing_id).toggle();
        $("#favorite_star_"+thing_id).toggle();
    }).catch(function() {
        console.log(url, 'error');
    })
}
</script>
{% endblock %}